- name: Deploy Webserver
  hosts: [red, blue]
  remote_user: root

  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Setup
      ansible.builtin.shell: |
        apt update
        apt install git
        apt install nodejs --assume-yes
        apt install npm --assume-yes
        apt install curl --assume-yes
        apt install nginx --assume-yes

    - name: Get Files 
      ansible.builtin.shell: |
        rm -rf CSE356-HW1
        git clone https://github.com/PeteyLumpkins/CSE356-HW1.git
   
    - name: Configure Web Server
      ansible.builtin.shell: |
        mv /root/CSE356-HW1/nginx-config/server.txt /etc/nginx/sites-available/default
        ln /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
        systemctl restart nginx

    - name: Configure Red Server 
      ansible.builtin.shell: |
        mv /root/CSE356-HW1/build/public/red.html /root/CSE356-HW1/build/public/hw1.html
        cd ..
        cd /var/www
        rm -rf ptwalsh
        mv /root/CSE356-HW1 /var/www/ptwalsh
        cd ptwalsh
        npm install
        nohup npm run start > foo.out 2> foo.err < /dev/null  &
      when: "'red' in group_names"
    
    - name: Configure Blue Server
      ansible.builtin.shell: |
        mv /root/CSE356-HW1/build/public/blue.html /root/CSE356-HW1/build/public/hw1.html
        cd ..
        cd /var/www
        rm -rf ptwalsh
        mv /root/CSE356-HW1 /var/www/ptwalsh
        cd ptwalsh
        npm install
        nohup npm run start > foo.out 2> foo.err < /dev/null  &
      when: "'blue' in group_names"